### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by sariyamelody** [brocaar/nginx-rtmp-dockerfile#1]
Hi,

I'd like to be able to formally contribute to this project, but as there is no LICENSE I will be forced to greenfield my own configuration. I would love if this project was liberally licensed e.g. MIT/BSD!

**Comment by macbroadcast** [comment]
...i believe this is the licence and the obvious reason why there is no such file in here :smile:

https://github.com/arut/nginx-rtmp-module/blob/master/LICENSE

**Comment by sariyamelody** [comment]
I more specifically meant a license on your Dockerfile and nginx
configuration :-)

For expansion, I'm in the process of writing a turnkey streaming
solution using this and jwplayer as the basis. Free and open source!

**Comment by macbroadcast** [comment]
You did not understand what i wrote ? I said the reason why  there is no licence file is because its copyrighted :smiley:
