### ISSUE TITLE
Cant install dock

### ISSUE THREAD

**Issue by Disinterpreter** [brocaar/nginx-rtmp-dockerfile#4]
I can't install dock:
press: docker build -t nginx_rtmp .

my system: #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

xenial has ffmpeg on self repos.

`Reading package lists...
W: The repository 'http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/mc3man/trusty-media/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update' returned a non-zero code: 100
`

**Comment by Disinterpreter** [comment]
I fix in #6

**Comment by brocaar** [comment]
pr has been merged, should be fixed now.
