### ISSUE TITLE
Can't connect how it's write on README

### ISSUE THREAD

**Issue by Disinterpreter** [brocaar/nginx-rtmp-dockerfile#5]
Can't connect how it's wrote on README

Stream your live content to rtmp://localhost:1935/encoder/stream_name where stream_name is the name of your stream.

I write: rtmp://myipv4:1935/encoder/stream
and get: 
http://i.imgur.com/4IgbCHI.png
But if i do rtmp://myipv4:1935/encoder
and Play path. Stream is working, but hls doesn't work.

Stat log:
`1.6.2
1.1.4
gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.1) 
Jul 17 2016 14:35:13
6
6444
191
2438392
379007999
1485568
180462723
encoder
stream
16451742477928
161258879
1486216
128390432
255832
2222088
17191.247.155.172422378FMLE/3.0 (compatible; FMSc/1.0)rtmp://myipv4.ru:1935/encoder027420736
128072024H264Main644.1AACLC248000
1 1 hls 0
`

P.S /data/hls is empty

root@471fa8485c3c:/data/hls# pwd
/data/hls
root@471fa8485c3c:/data/hls# ls -all
total 8
drwx------ 2 nobody root 4096 Jul 17 15:57 .
drwxr-xr-x 3 root   root 4096 Jul 17 14:36 ..
root@471fa8485c3c:/data/hls#

**Comment by Disinterpreter** [comment]
too fixed on #6

**Comment by brocaar** [comment]
Cheers for your pull request 👍
